### ISSUE TITLE
Installation error in FreeBSD

### ISSUE THREAD

**Issue by raidancampbell** [zeromq/lzmq#43]
OS: FreeBSD 9.3

`luarocks --version`:

    /root/torch/install/bin/luarocks 2.2.0beta1
    LuaRocks main command-line interface

`lua -v`:
    
    Lua 5.2.3  Copyright (C) 1994-2013 Lua.org, PUC-Rio

command run: `luarocks install lzmq &> lzmq_install.txt`

output:

    Archive:  v0.4.3.zip
	d lzmq-0.4.3
	 extracting: lzmq-0.4.3/.gitignore
	 extracting: lzmq-0.4.3/.travis.yml
	d lzmq-0.4.3/.travis
	 extracting: lzmq-0.4.3/.travis/platform.sh
	 extracting: lzmq-0.4.3/.travis/setup_lua.sh
	 extracting: lzmq-0.4.3/.travis/setup_sodium.sh
	 extracting: lzmq-0.4.3/.travis/setup_zmq.sh
	 extracting: lzmq-0.4.3/CMakeLists.txt
	 extracting: lzmq-0.4.3/LICENCE.txt
	 extracting: lzmq-0.4.3/README.md
	d lzmq-0.4.3/cmake
	 extracting: lzmq-0.4.3/cmake/FindLua.cmake
	 extracting: lzmq-0.4.3/cmake/FindZMQ.cmake
	 extracting: lzmq-0.4.3/cmake/dist.cmake
	 extracting: lzmq-0.4.3/cmake/lua.cmake
	 extracting: lzmq-0.4.3/dist.info
	d lzmq-0.4.3/doc
	 extracting: lzmq-0.4.3/doc/lzmq.ldoc
	d lzmq-0.4.3/doc/lzmq
	 extracting: lzmq-0.4.3/doc/lzmq/loop.ldoc
	 extracting: lzmq-0.4.3/doc/lzmq/poller.ldoc
	 extracting: lzmq-0.4.3/doc/lzmq/threads.ldoc
	 extracting: lzmq-0.4.3/doc/lzmq/timer.ldoc
	d lzmq-0.4.3/examples
	d lzmq-0.4.3/examples/device
	 extracting: lzmq-0.4.3/examples/device/cli.lua
	 extracting: lzmq-0.4.3/examples/device/device.lua
	 extracting: lzmq-0.4.3/examples/device/srv.lua
	 extracting: lzmq-0.4.3/examples/echo_cli.lua
	 extracting: lzmq-0.4.3/examples/echo_loop.lua
	 extracting: lzmq-0.4.3/examples/echo_loop_raw.lua
	 extracting: lzmq-0.4.3/examples/monitor.lua
	d lzmq-0.4.3/examples/perf
	 extracting: lzmq-0.4.3/examples/perf/local_lat.lua
	 extracting: lzmq-0.4.3/examples/perf/local_multipart.lua
	 extracting: lzmq-0.4.3/examples/perf/local_thr.lua
	 extracting: lzmq-0.4.3/examples/perf/remote_lat.lua
	 extracting: lzmq-0.4.3/examples/perf/remote_multipart.lua
	 extracting: lzmq-0.4.3/examples/perf/remote_thr.lua
	 extracting: lzmq-0.4.3/examples/perf/test_lat.bat
	 extracting: lzmq-0.4.3/examples/perf/test_multipart.bat
	 extracting: lzmq-0.4.3/examples/perf/test_thr.bat
	 extracting: lzmq-0.4.3/examples/perf/thread_lat.lua
	 extracting: lzmq-0.4.3/examples/perf/thread_thr.lua
	d lzmq-0.4.3/examples/perf2
	d lzmq-0.4.3/examples/perf2/lat
	 extracting: lzmq-0.4.3/examples/perf2/lat/inproc_lat.lua
	 extracting: lzmq-0.4.3/examples/perf2/lat/local_lat.lua
	 extracting: lzmq-0.4.3/examples/perf2/lat/remote_lat.lua
	d lzmq-0.4.3/examples/perf2/lat_nomsg
	 extracting: lzmq-0.4.3/examples/perf2/lat_nomsg/inproc_lat.lua
	 extracting: lzmq-0.4.3/examples/perf2/lat_nomsg/local_lat.lua
	 extracting: lzmq-0.4.3/examples/perf2/lat_nomsg/remote_lat.lua
	 extracting: lzmq-0.4.3/examples/perf2/runner.lua
	d lzmq-0.4.3/examples/perf2/thr
	 extracting: lzmq-0.4.3/examples/perf2/thr/inproc_thr.lua
	 extracting: lzmq-0.4.3/examples/perf2/thr/local_thr.lua
	 extracting: lzmq-0.4.3/examples/perf2/thr/remote_thr.lua
	d lzmq-0.4.3/examples/perf2/thr_nomsg
	 extracting: lzmq-0.4.3/examples/perf2/thr_nomsg/inproc_thr.lua
	 extracting: lzmq-0.4.3/examples/perf2/thr_nomsg/local_thr.lua
	 extracting: lzmq-0.4.3/examples/perf2/thr_nomsg/remote_thr.lua
	 extracting: lzmq-0.4.3/examples/queue_device.lua
	 extracting: lzmq-0.4.3/examples/utils.lua
	 extracting: lzmq-0.4.3/examples/uv_actor.lua
	 extracting: lzmq-0.4.3/examples/zap.lua
	 extracting: lzmq-0.4.3/lakeconfig.lua
	 extracting: lzmq-0.4.3/lakefile
	d lzmq-0.4.3/msvc
	 extracting: lzmq-0.4.3/msvc/luazmq.sln
	 extracting: lzmq-0.4.3/msvc/luazmq.vcproj
	 extracting: lzmq-0.4.3/msvc/lztimer.vcproj
	d lzmq-0.4.3/rockspecs
	 extracting: lzmq-0.4.3/rockspecs/lzmq-0.1.0-1.rockspec
	 extracting: lzmq-0.4.3/rockspecs/lzmq-0.1.1-1.rockspec
	 extracting: lzmq-0.4.3/rockspecs/lzmq-0.1.2-1.rockspec
	 extracting: lzmq-0.4.3/rockspecs/lzmq-0.1.3-1.rockspec
	 extracting: lzmq-0.4.3/rockspecs/lzmq-0.2.0-1.rockspec
	 extracting: lzmq-0.4.3/rockspecs/lzmq-0.3.0-1.rockspec
	 extracting: lzmq-0.4.3/rockspecs/lzmq-0.3.1-1.rockspec
	 extracting: lzmq-0.4.3/rockspecs/lzmq-0.3.2-1.rockspec
	 extracting: lzmq-0.4.3/rockspecs/lzmq-0.3.3-1.rockspec
	 extracting: lzmq-0.4.3/rockspecs/lzmq-0.3.4-1.rockspec
	 extracting: lzmq-0.4.3/rockspecs/lzmq-0.3.5-1.rockspec
	 extracting: lzmq-0.4.3/rockspecs/lzmq-0.3.6-1.rockspec
	 extracting: lzmq-0.4.3/rockspecs/lzmq-0.4.0-1.rockspec
	 extracting: lzmq-0.4.3/rockspecs/lzmq-0.4.1-1.rockspec
	 extracting: lzmq-0.4.3/rockspecs/lzmq-0.4.2-1.rockspec
	 extracting: lzmq-0.4.3/rockspecs/lzmq-0.4.3-1.rockspec
	 extracting: lzmq-0.4.3/rockspecs/lzmq-ffi-0.1.3-1.rockspec
	 extracting: lzmq-0.4.3/rockspecs/lzmq-ffi-0.2.0-1.rockspec
	 extracting: lzmq-0.4.3/rockspecs/lzmq-ffi-0.3.0-1.rockspec
	 extracting: lzmq-0.4.3/rockspecs/lzmq-ffi-0.3.1-1.rockspec
	 extracting: lzmq-0.4.3/rockspecs/lzmq-ffi-0.3.2-1.rockspec
	 extracting: lzmq-0.4.3/rockspecs/lzmq-ffi-0.3.3-1.rockspec
	 extracting: lzmq-0.4.3/rockspecs/lzmq-ffi-0.3.4-1.rockspec
	 extracting: lzmq-0.4.3/rockspecs/lzmq-ffi-0.3.5-1.rockspec
	 extracting: lzmq-0.4.3/rockspecs/lzmq-ffi-0.3.6-1.rockspec
	 extracting: lzmq-0.4.3/rockspecs/lzmq-ffi-0.4.0-1.rockspec
	 extracting: lzmq-0.4.3/rockspecs/lzmq-ffi-0.4.1-1.rockspec
	 extracting: lzmq-0.4.3/rockspecs/lzmq-ffi-0.4.2-1.rockspec
	 extracting: lzmq-0.4.3/rockspecs/lzmq-ffi-0.4.3-1.rockspec
	 extracting: lzmq-0.4.3/rockspecs/lzmq-ffi-scm-0.rockspec
	 extracting: lzmq-0.4.3/rockspecs/lzmq-scm-0.rockspec
	 extracting: lzmq-0.4.3/rockspecs/lzmq-timer-0.1.2-1.rockspec
	 extracting: lzmq-0.4.3/rockspecs/lzmq-timer-0.3.5-1.rockspec
	 extracting: lzmq-0.4.3/rockspecs/lzmq-timer-0.4.2-1.rockspec
	 extracting: lzmq-0.4.3/rockspecs/lzmq-timer-scm-0.rockspec
	d lzmq-0.4.3/script
	 extracting: lzmq-0.4.3/script/getsockopt.lua
	d lzmq-0.4.3/src
	d lzmq-0.4.3/src/lua
	d lzmq-0.4.3/src/lua/lzmq
	 extracting: lzmq-0.4.3/src/lua/lzmq/ffi.lua
	d lzmq-0.4.3/src/lua/lzmq/ffi
	 extracting: lzmq-0.4.3/src/lua/lzmq/ffi/api.lua
	 extracting: lzmq-0.4.3/src/lua/lzmq/ffi/error.lua
	 extracting: lzmq-0.4.3/src/lua/lzmq/ffi/loop.lua
	 extracting: lzmq-0.4.3/src/lua/lzmq/ffi/lzmq.lua
	 extracting: lzmq-0.4.3/src/lua/lzmq/ffi/poller.lua
	 extracting: lzmq-0.4.3/src/lua/lzmq/ffi/threads.lua
	 extracting: lzmq-0.4.3/src/lua/lzmq/ffi/timer.lua
	d lzmq-0.4.3/src/lua/lzmq/impl
	 extracting: lzmq-0.4.3/src/lua/lzmq/impl/loop.lua
	 extracting: lzmq-0.4.3/src/lua/lzmq/impl/threads.lua
	d lzmq-0.4.3/src/lua/lzmq/llthreads
	 extracting: lzmq-0.4.3/src/lua/lzmq/llthreads/ex.lua
	 extracting: lzmq-0.4.3/src/lua/lzmq/loop.lua
	 extracting: lzmq-0.4.3/src/lua/lzmq/poller.lua
	 extracting: lzmq-0.4.3/src/lua/lzmq/threads.lua
	 extracting: lzmq-0.4.3/src/lzmq.c
	 extracting: lzmq-0.4.3/src/lzmq.def
	 extracting: lzmq-0.4.3/src/lzmq.h
	 extracting: lzmq-0.4.3/src/lzutils.c
	 extracting: lzmq-0.4.3/src/lzutils.h
	 extracting: lzmq-0.4.3/src/poller.c
	 extracting: lzmq-0.4.3/src/poller.h
	 extracting: lzmq-0.4.3/src/timer.def
	 extracting: lzmq-0.4.3/src/zcontext.c
	 extracting: lzmq-0.4.3/src/zcontext.h
	 extracting: lzmq-0.4.3/src/zerror.c
	 extracting: lzmq-0.4.3/src/zerror.h
	 extracting: lzmq-0.4.3/src/zmsg.c
	 extracting: lzmq-0.4.3/src/zmsg.h
	 extracting: lzmq-0.4.3/src/zpoller.c
	 extracting: lzmq-0.4.3/src/zpoller.h
	 extracting: lzmq-0.4.3/src/zsocket.c
	 extracting: lzmq-0.4.3/src/zsocket.h
	 extracting: lzmq-0.4.3/src/zsupport.h
	 extracting: lzmq-0.4.3/src/ztimer.c
	 extracting: lzmq-0.4.3/src/ztimer.h
	d lzmq-0.4.3/test
	 extracting: lzmq-0.4.3/test/.luacov
	 extracting: lzmq-0.4.3/test/.luacov.ffi
	d lzmq-0.4.3/test/lunit
	 extracting: lzmq-0.4.3/test/lunit/console.lua
	 extracting: lzmq-0.4.3/test/test.lua
	 extracting: lzmq-0.4.3/test/test_metadata.lua
	 extracting: lzmq-0.4.3/test/test_proxy.lua
	 extracting: lzmq-0.4.3/test/test_req_relaxed.lua
	 extracting: lzmq-0.4.3/test/test_threads.lua
	 extracting: lzmq-0.4.3/test/test_threads_actor.lua
	 extracting: lzmq-0.4.3/test/test_threads_actor_poll.lua
	 extracting: lzmq-0.4.3/test/test_threads_arg.lua
	 extracting: lzmq-0.4.3/test/test_threads_file.lua
	 extracting: lzmq-0.4.3/test/test_threads_fork.lua
	 extracting: lzmq-0.4.3/test/test_threads_fork_arg.lua
	 extracting: lzmq-0.4.3/test/test_threads_fork_opt.lua
	 extracting: lzmq-0.4.3/test/test_threads_opt.lua
	 extracting: lzmq-0.4.3/test/test_threads_sync.lua
	 extracting: lzmq-0.4.3/test/thread.lua
	 extracting: lzmq-0.4.3/test/utest.lua
    cc -O2 -fPIC -I/root/torch/install/include -c src/lzmq.c -o src/lzmq.o -DLUAZMQ_USE_SEND_AS_BUF -DLUAZMQ_USE_TEMP_BUFFERS -DLUAZMQ_USE_ERR_TYPE_OBJECT -I/usr/local/include
    src/lzmq.c: In function 'luazmq_z85_encode':
    src/lzmq.c:366: warning: incompatible implicit declaration of built-in function 'malloc'
    src/lzmq.c: In function 'luazmq_z85_decode':
    src/lzmq.c:386: warning: incompatible implicit declaration of built-in function 'malloc'
    cc -O2 -fPIC -I/root/torch/install/include -c src/lzutils.c -o src/lzutils.o -DLUAZMQ_USE_SEND_AS_BUF -DLUAZMQ_USE_TEMP_BUFFERS -DLUAZMQ_USE_ERR_TYPE_OBJECT -I/usr/local/include
    cc -O2 -fPIC -I/root/torch/install/include -c src/poller.c -o src/poller.o -DLUAZMQ_USE_SEND_AS_BUF -DLUAZMQ_USE_TEMP_BUFFERS -DLUAZMQ_USE_ERR_TYPE_OBJECT -I/usr/local/include
    cc -O2 -fPIC -I/root/torch/install/include -c src/zcontext.c -o src/zcontext.o -DLUAZMQ_USE_SEND_AS_BUF -DLUAZMQ_USE_TEMP_BUFFERS -DLUAZMQ_USE_ERR_TYPE_OBJECT -I/usr/local/include
    cc -O2 -fPIC -I/root/torch/install/include -c src/zerror.c -o src/zerror.o -DLUAZMQ_USE_SEND_AS_BUF -DLUAZMQ_USE_TEMP_BUFFERS -DLUAZMQ_USE_ERR_TYPE_OBJECT -I/usr/local/include
    cc -O2 -fPIC -I/root/torch/install/include -c src/zmsg.c -o src/zmsg.o -DLUAZMQ_USE_SEND_AS_BUF -DLUAZMQ_USE_TEMP_BUFFERS -DLUAZMQ_USE_ERR_TYPE_OBJECT -I/usr/local/include
    cc -O2 -fPIC -I/root/torch/install/include -c src/zpoller.c -o src/zpoller.o -DLUAZMQ_USE_SEND_AS_BUF -DLUAZMQ_USE_TEMP_BUFFERS -DLUAZMQ_USE_ERR_TYPE_OBJECT -I/usr/local/include
    cc -O2 -fPIC -I/root/torch/install/include -c src/zsocket.c -o src/zsocket.o -DLUAZMQ_USE_SEND_AS_BUF -DLUAZMQ_USE_TEMP_BUFFERS -DLUAZMQ_USE_ERR_TYPE_OBJECT -I/usr/local/include
    cc -shared -o lzmq.so -L/root/torch/install/lib src/lzmq.o src/lzutils.o src/poller.o src/zcontext.o src/zerror.o src/zmsg.o src/zpoller.o src/zsocket.o -L/usr/local/lib -lzmq
    /usr/bin/ld: cannot find -lzmq

    Error: Build error: Failed compiling module lzmq.so

**Comment by raidancampbell** [comment]
...turns out you need ZMQ installed to use LZMQ...

**Comment by moteus** [comment]
I have no access to FreeBSD.
1. To fix warning you need include `stdlib.h`. Please test it.
2. Linker can not find libzmq. Try specify ZMQ_LIB_DIR manually.
Sorry but I never work on BSD system and do not know how linker search library.
