### ISSUE TITLE
lzmq installation problems

### ISSUE THREAD

**Issue by victorlempitsky** [zeromq/lzmq#46]
Fresh installation of Torch7 distribution, followed by the successful installation of lzmq:

>  luarocks install lzmq 
> .....
>  lzmq 0.4.3-1 is now built and installed in /home/vilem/torch/install/ (license: MIT/X11)

However, loading of lzmq fails:

>  th> require 'lzmq'
> /home/vilem/torch/install/share/lua/5.1/trepl/init.lua:384: /home/vilem/torch/install/share/lua/5.1/luarocks/loader.lua:117: error loading module 'lzmq' from file '/home/vilem/torch/install/lib/luarocks/rocks/lzmq':
>   cannot read /home/vilem/torch/install/lib/luarocks/rocks/lzmq: Is a directory
> stack traceback:
>   [C]: in function 'error'
>   /home/vilem/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
>   [string "_RESULT={require 'lzmq'}"]:1: in main chunk
>   [C]: in function 'xpcall'
>   /home/vilem/torch/install/share/lua/5.1/trepl/init.lua:651: in function 'repl'
>   ...ilem/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
>   [C]: at 0x00406670  

Ubuntu 14.04. 
I noticed that installing lzmq-ffi with luarocks solves the problem, however these bindings are not suitable for iTorch, so this does not solve my problem.
I would be very grateful for any help.

**Comment by moteus** [comment]
I think this is problem with loader you use.
It should not search any info in `.../luarocks/rocks/...` dir.
`require"lzmq"` shuld find `lzmq.so` file.
On debian by default it in
`/usr/local/lib/lua/5.2/lzmq.so`
`/usr/local/lib/lua/5.2/lzmq/timer.so`
and Lua files in `/usr/local/share/lua/5.2/lzmq/` directory.
`/usr/local/lib/luarocks/rocks/lzmq` contain installed files like test and examples.

**Comment by victorlempitsky** [comment]
Hi, thanks a lot for your reply and sorry for a slow responce. Somehow, creating the default structure that you describe does not help, as the torch/lua distribution is installed locally. All other packages (that I have tried) except lzmq work... Any ideas how to specify paths for  " require 'lzmq' " to look at?
