### ISSUE TITLE
How can I use it with embedded Lua / LuaJIT?

### ISSUE THREAD

**Issue by furjoy** [zeromq/lzmq#47]

**Comment by moteus** [comment]
With LuaJIT you can just use `lzmq-ffi` module. But lzmq.timer still need to build.
If you link Lua staticly then it depends on OS.
On Windows you have to export Lua API from application and link dll with it.
On Linux I think you do not need link library with Lua and you can just load any dynamic library.

**Comment by furjoy** [comment]
Thank you for the fast responce.
I chose to statically link lzmq to my embedded LuaJIT app.
Eventually, I have added 
```c
LUAZMQ_EXPORT int luaopen_lzmq (lua_State *L);
```
into lzmq.h to make it work.
