### ISSUE TITLE
Is curve authentication possible with lzmq?

### ISSUE THREAD

**Issue by mweinelt** [zeromq/lzmq#65]
Hi,

I've seen lzmq can generate a curve keypair, but I'm not sure where to set it so that the socket makes use of it. Is that even possible?

**Comment by moteus** [comment]
I think you can checkout [lzmq-auth](https://github.com/moteus/lzmq-auth) module. I did not use it actually, but it implement [zmq auth protocol](https://rfc.zeromq.org/spec:27/ZAP/). May be it quite outdated thou. You can just read about it an use it directly
